export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const GET_CURRENT_SUBJECT = "GET_CURRENT_SUBJECT";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SOFT_DELETE_USER = "SOFT_DELETE_USER"

export const GET_ALL_TOPICS = "GET_ALL_TOPICS";
export const ADD_TOPIC = "ADD_TOPIC";
export const UPDATE_TOPIC = "UPDATE_TOPIC";
export const DELETE_TOPIC = "DELETE_TOPIC";
export const GET_CURRENT_TOPIC = "GET_CURRENT_TOPIC";
export const GET_TOPICS_BYQUESTIONID= "GET_TOPICS_BYQUESTIONID"
export const GET_TOPICS_BYSUBJECT = "GET_TOPICS_BYSUBJECT"

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const GET_CURRENT_QUESTION = "GET_CURRENT_QUESTION";
export const GET_QUESTIONS_BY_SUBJECT = "GET_QUESTIONS_BY_SUBJECT";
export const ACTIVE_QUESTION = "ACTIVE_QUESTION";

export const GET_ALL_PAPERS = "GET_ALL_PAPERS";
export const ADD_PAPER = "ADD_PAPER";
export const UPDATE_PAPER = "UPDATE_PAPER";
export const DELETE_PAPER = "DELETE_PAPER";
export const GET_CURRENT_PAPER = "GET_CURRENT_PAPERS";

export const GET_ALL_PAPER_QUESTIONS = "GET_ALL_PAPER_QUESTIONS";
export const ADD_PAPER_QUESTION = "ADD_PAPER_QUESTION";
export const UPDATE_PAPER_QUESTION = "UPDATE_PAPER_QUESTION";
export const DELETE_PAPER_QUESTION = "DELETE_PAPER_QUESTION";
export const GET_CURRENT_PAPER_QUESTION = "GET_CURRENT_PAPER_QUESTION";
export const GET_PAPER_QUESTIONS_BYPAPER = "GET_PAPER_QUESTIONS_BYPAPER"
export const FILTER_QUESTIONS = "FILTER_QUESTIONS"
export const CLEAR_PAPER_QUESTIONS = "CLEAR_PAPER_QUESTIONS"
export const EXAM_QUESTIONNS = "EXAM_QUESTIONNS"

export const GET_ALL_STUDENT_PAPERS = "GET_ALL_STUDENT_PAPERS";
export const ADD_STUDENT_PAPER = "ADD_STUDENT_PAPER";
export const UPDATE_STUDENT_PAPER = "UPDATE_STUDENT_PAPER";
export const DELETE_STUDENT_PAPER = "DELETE_STUDENT_PAPER";
export const GET_CURRENT_STUDENT_PAPER = "GET_CURRENT_STUDENT_PAPER";
export const GET_STUDENT_PAPERS_BYSTUDENTS = "GET_STUDENT_PAPERS_BYSTUDENTS";
export const GET_RESULT_BYSTUDENT = "GET_RESULT_BYSTUDENT"


export const GET_ALL_STUDENT_ANSWERS= "GET_ALL_STUDENT_ANSWERS";
export const ADD_STUDENT_ANSWER = "ADD_STUDENT_ANSWER";
export const UPDATE_STUDENT_ANSWER = "UPDATE_STUDENT_ANSWER";
export const DELETE_STUDENT_ANSWER = "DELETE_STUDENT_ANSWER";
export const GET_CURRENT_STUDENT_ANSWER = "GET_CURRENT_STUDENT_ANSWER";
export const GET_STUDENT_ANSWERS_STUDENTANDPAPER = "GET_STUDENT_ANSWERS_STUDENTANDPAPER";
export const CLEAR_STUDENT_ANSWERS = "CLEAR_STUDENT_ANSWERS";



export const GET_ALL_ANSWEROPTIONS = "GET_ALL_ANSWEROPTIONS";
export const GET_ANSWEROPTIONS_BYQUESTIONID = "GET_ANSWEROPTIONS_BYQUESTIONID";

